name: Initialize-PSModule (by PSModule)
description: Prepare runner for the PSModule framework.
author: PSModule
branding:
  icon: loader
  color: gray-dark

runs:
  using: composite
  steps:
    - name: Install GitHub
      shell: pwsh
      run: |
        # Install GitHub
        $params = @{
          Name            = 'GitHub'
          Repository      = 'PSGallery'
          TrustRepository = $true
          Verbose         = $true
        }
        Install-PSResource @params
        Import-Module -Name 'GitHub' -Force -Verbose

    - name: Run Initialize-PSModule
      shell: pwsh
      run: |
        . "$env:GITHUB_ACTION_PATH\scripts\main.ps1" -Verbose
