name: Initialize-PSModule (by PSModule)
description: Prepare runner for the PSModule framework.
author: PSModule
branding:
  icon: loader
  color: gray-dark

runs:
  using: composite
  steps:
    - name: Initialize-PSModule
      uses: PSModule/GitHub-Script@v1
      with:
        Script: |
          # Initialize-PSModule
          . "${{ github.action_path }}\scripts\main.ps1" -Verbose
