name: Initialize-PSModule
description: Initialize/Install PSModule framework on the runner
branding:
  icon: activity
  color: blue

inputs:
  Version:
    description: The version of the module to install.
    required: false
  Verbose:
    description: Enable verbose output.
    required: false
    default: 'true'
  WhatIf:
    description: Run in WhatIf mode.
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: Run Initialize-PSModule
      shell: pwsh
      env:
        Version: ${{ inputs.Version }}
        Verbose: ${{ inputs.Verbose }}
        WhatIf: ${{ inputs.WhatIf }}
      run: . "$env:GITHUB_ACTION_PATH\scripts\main.ps1"
