name: Action-Test

run-name: "Action-Test - [${{ github.event.pull_request.title }} #${{ github.event.pull_request.number }}] by @${{ github.actor }}"

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  ActionTestBasic:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    name: Action-Test - [Basic] - [${{ matrix.os }}]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Action-Test
        uses: ./
        with:
          env: |
            TEST_APP_CLIENT_ID: ${{ secrets.TEST_APP_CLIENT_ID }}
            TEST_APP_PRIVATE_KEY: ${{ toJson(secrets.TEST_APP_PRIVATE_KEY) }}
            TEST_FG_PAT: ${{ secrets.TEST_FG_PAT }}
            TEST_PAT: ${{ secrets.TEST_PAT }}

      - name: Run GitHub-script
        uses: PSModule/GitHub-script@v1
        with:
          Script: |
            LogGroup "Run custom script" {
                Write-Host "Hello, World!"
                "ClientID is : [$env:TEST_APP_CLIENT_ID]"
            }

      - name: Run custom script
        shell: pwsh
        run: |
          LogGroup "Run custom script" {
              Write-Host "Hello, World!"
          }
