name: Verify Action

on:
  workflow_call:
  push:
    branches-ignore:
      - main
    paths:
      - action.yml
      - .github/workflows/Action-Test.yml
      - Modules/**
      - Scripts/**
  pull_request:
    branches:
      - main
    paths:
      - action.yml
      - .github/workflows/Action-Test.yml
      - Modules/**
      - Scripts/**

jobs:
  DefaultTest:
    name: Test Action - [Default]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Test local action
        uses: ./
