name: Verify Action

on:
  workflow_call:
  push:
    branches-ignore:
      - main
    paths:
      - action.yml
      - .github/workflows/Action-Test.yml
      - scripts/**
  pull_request:
    branches:
      - main
    paths:
      - action.yml
      - .github/workflows/Action-Test.yml
      - scripts/**
env:
  COMMIT_SHA: ${{ github.sha }}

jobs:
  DefaultTest:
    name: Test Action - [Default]
    runs-on: ubuntu-latest
    steps:
      - name: Initialize environment
        uses: PSModule/Initialize-PSModule@${{ env.COMMIT_SHA }}
