name: Linter

on:
  workflow_call:
  push:
    paths:
      - action.yml
      - .github/workflows/Action-Test.yml
      - Modules/**
      - Scripts/**
  pull_request:
    branches:
      - main
    paths:
      - action.yml
      - .github/workflows/Action-Test.yml
      - Modules/**
      - Scripts/**

jobs:
  Lint:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Lint Code Base
        uses: github/super-linter@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
