name: Linter

on:
  workflow_call:
  push:
    branches-ignore:
      - main
    paths:
      - action.yml
      - .github/workflows/Action-Test.yml
      - scripts/**
  pull_request:
    branches:
      - main
    paths:
      - action.yml
      - .github/workflows/Action-Test.yml
      - scripts/**

jobs:
  Lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Lint code base
        uses: github/super-linter@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
