name: Linter

on: [push]

jobs:
  Lint:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Lint Code Base
        uses: github/super-linter@latest
